# Práctica 6

## Numpy

In [2]:
import numpy as np

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

a) Crea una lista nativa de Python llamada lista que contenga los números enteros del 0 al 5.

Utiliza la función adecuada de NumPy (np.array()) para transformar esa lista en un arreglo unidimensional (vector) llamado arreglo.

Imprime en pantalla ambos objetos utilizando la función print().

Pregunta de observación: Mira con atención el resultado en la consola. ¿Qué diferencia visual notas en la forma en que Python imprime la lista en comparación con el arreglo de NumPy?

In [5]:
listaNew = [0,1,2,3,4,5]
arrayNp = np.array([6,7,8,9,10,11])
print(listaNew)
print(arrayNp)

[0, 1, 2, 3, 4, 5]
[ 6  7  8  9 10 11]


b) Creación de Matrices (Arrays Bidimensionales)
Crea una lista de listas en Python llamada lista que contenga dos sublistas: la primera con los números del 0 al 4, y la segunda con los números del 5 al 9.

Transforma esta estructura en un arreglo de NumPy llamado arreglo.

Imprime el resultado en pantalla utilizando print().

Preguntas de análisis: 1) Al imprimirse en la consola, ¿cómo organiza NumPy las listas internas? ¿Se ve como una línea continua o como una estructura de filas y columnas?
2) Si agregas una celda de código abajo y ejecutas print(arreglo.shape), ¿qué dos números te devuelve NumPy y qué significa cada uno en términos de "filas" y "columnas"?

In [ ]:
listaDeListas = [[0,1,2,3,4], [5,6,7,8,9]]
# print(listaDeListas)

arreglo = np.array(listaDeListas)
# print(arreglo)
print(arreglo.shape) #! imprime el tamaño de la "matriz"

#* 1) se formatea y se muestra como una matriz - 2) numpy devuelve la dimension de la matriz

(2, 5)


c) Crea una variable llamada lista utilizando la función constructora list() combinada con range() para generar de forma directa los números enteros del 0 al 7.

Crea una segunda lista vacía llamada lista_2. Luego, utilizando un ciclo for y el método .append(), recorre el mismo rango de números para agregarlos uno a uno dentro de esa lista vacía.

Imprime en pantalla ambas listas y comprueba sus contenidos.

Preguntas de reflexión: 1) Si ambas listas terminan conteniendo exactamente los mismos elementos [0, 1, 2, 3, 4, 5, 6, 7], ¿cuál de los dos métodos requirió menos líneas de código y te parece más eficiente para el programador?
2) Si tuvieras que generar un millón de números, ¿cuál de las dos formas crees que tardaría menos tiempo en procesarse?

In [17]:
lista = list(range(0, 8))
print("Con range: ", lista)

lista2 = []
for i in lista:
    lista2.append(i)

print("Con for: ", lista2) 

#* 1) El primero es mas eficiente - 2) la segunda creo ya que no iteraria tanto como el for, pondria un list(range(0,1000000))   


Con range:  [0, 1, 2, 3, 4, 5, 6, 7]
Con for:  [0, 1, 2, 3, 4, 5, 6, 7]


e) En Python nativo, las operaciones matemáticas no se aplican automáticamente a cada elemento de una lista. NumPy resuelve esto mediante la vectorización.

Sigue los pasos a continuación para comprobarlo:

El error con Listas Nativas: Intenta ejecutar el siguiente código y observa el tipo de error (TypeError) que arroja Python en la consola:

Python
lista = [1, 2, 3, 4, 5]
Intento de sumarle 1 a cada elemento:
print(lista + 1)
(Nota: Para hacer esto con una lista, estarías obligado a usar un ciclo for).

La solución con NumPy (Operaciones Elemento por Elemento): Ahora, transforma esa lista en un array de NumPy y ejecuta las siguientes operaciones matemáticas directas:

Python
import numpy as np
arreglo = np.array([1, 2, 3, 4, 5])

Operación A: Sumarle un mismo número a todos los elementos
arreglo_sumado = arreglo + 1
print("Array + 1:", arreglo_sumado)

Operación B: Elevar al cuadrado todos los elementos al mismo tiempo
arreglo_cuadrado = arreglo ** 2
print("Array al cuadrado:", arreglo_cuadrado)
Pregunta de reflexión: Explicá con tus palabras qué ventaja ofrece NumPy al permitirnos escribir arreglo + 1 en lugar de tener que armar un ciclo for para recorrer la lista elemento por elemento.

In [ ]:
listita = [1, 2, 3, 4, 5]
# print(lista+1) No funciona

arreglito = np.array([1,2,3,4,5])
arreglitoSumado = arreglito + 1
arregloCuadrado = arreglito ** 2
print(arreglito)
print(arreglitoSumado) #? Le suma uno a cada numero
print(arregloCuadrado) #? cada numero al cuadrado

#* Numpy nos permite manipular con numeros de forma mucho mas sencilla


[1 2 3 4 5]
[2 3 4 5 6]
[ 1  4  9 16 25]


Cuando trabajamos con grandes volúmenes de datos, una de las tareas más comunes es resumirlos (calcular el total, el promedio, el máximo, etc.). Vamos a comparar cómo se hace esto en Python nativo versus NumPy.

El error con Listas Nativas: Intenta ejecutar el siguiente código y observa el error en la consola:

Python
lista = [10, 20, 30, 40]
# Intento de usar un método .sum() en una lista:
print(lista.sum())
La solución nativa: Para sumar una lista en Python sin usar NumPy, estás obligado a usar una función externa llamada sum(). Pruébalo así:

Python
print(sum(lista))
La solución eficiente con NumPy: Transforma la lista en un array y utiliza el método propio de NumPy .sum(). Este método está optimizado para ejecutarse a nivel de memoria de forma ultra rápida:

Python
import numpy as np
arreglo = np.array([10, 20, 30, 40])

print(arreglo.sum())
Pregunta de análisis: ¿Cuál es la diferencia en la sintaxis entre usar la función sum(lista) y el método arreglo.sum()? ¿A qué objeto le pertenece cada una?

In [30]:
listeta = [10, 20, 30, 40]
print("Sin Numpy: ", sum(listeta))

listetaNp = np.array(listeta)
print("Con Numpy: ", listetaNp.sum())

#* Una pertenece a Python nativo, la otra a un metodo de Numpy, que segun la consigna es mas eficiente y rapido a nivel memoria.

Sin Numpy:  100
Con Numpy:  100


d) Crea una lista nativa de Python llamada lista_mixta que contenga los elementos: [10, "Ciencia de Datos", 3.14, True]. Imprime su contenido y su tipo de objeto con type().
2. Crea un arreglo de NumPy llamado array_int a partir de la lista numérica [1, 2, 3, 4, 5]. Imprime el array y observa el atributo .dtype. ¿Qué tipo de datos almacena?
3. Intenta crear un arreglo de NumPy a partir de lista_mixta. Imprime el resultado y el .dtype.

Pregunta de reflexión: ¿Qué le ocurrió a los números y al booleano dentro del array de NumPy? ¿Por qué NumPy hace esto?

In [ ]:
listaMixta = [10, "Ciencia de Datos", 3.14, True]
print(listaMixta, " - ", type(listaMixta)) #? Lista heterogenea

arrayInt = np.array([1,2,3,4,5])
print(arrayInt, " - ", arrayInt.dtype) #? Array homogeneo de enteros

arrayada = np.array(listaMixta)
print(arrayada, " - ", arrayada.dtype) #? Convierte a strings: Unicode string - hasta 32 caracteres


[10, 'Ciencia de Datos', 3.14, True]  -  <class 'list'>
[1 2 3 4 5]  -  int64
['10' 'Ciencia de Datos' '3.14' 'True']  -  <U32


**Ejercicio 2**:
*Para este ejercicio vamos a usar una herramienta de Jupyter llamada %timeit. Este es un comando que analiza la línea de código que tiene a la derecha, la ejecuta miles de veces automáticamente y calcula el tiempo promedio que tardó en completarse.

¿Cómo leer los resultados de %timeit?
Te va a mostrar el tiempo usando diferentes unidades médicas de tiempo:

ms (Milisegundos): La milésima parte de un segundo.

µs (Microsegundos): ¡La millonésima parte de un segundo! (Es decir, muchísimo más rápido).

Consigna: Escribe el código correspondiente en dos celdas separadas de tu cuaderno para comparar cuánta ventaja nos da trabajar con NumPy al procesar un millón de datos.

Celda A: El camino tradicional con Listas Nativas
Crea dos listas independientes llamadas lista_A y lista_B, cada una con los números del 0 al 999.999 usando list(range(1000000)).

Crea una tercera lista vacía llamada lista_resultado.

Escribe un ciclo for que recorra el rango de ese millón de elementos. Dentro del bucle, suma el elemento de la lista_A con el de la lista_B en la misma posición usando sus índices, y agrega el resultado a lista_resultado usando .append().

Al principio de la línea del bucle for, coloca el comando %timeit separado por un espacio para medir cuánto tarda Python en hacer todo ese recorrido.

In [51]:
listaA = list(range(1000000))
listaB = list(range(1000000))
listaResultado = []


%timeit for i in range(len(listaA)):
    listaResultado.append(listaA[i] + listaB[i])

IndentationError: unexpected indent (727954097.py, line 7)

Celda B: El camino ultra rápido con NumPy

Crea dos arrays llamados array_A y array_B usando np.arange(1000000).

En una nueva línea, escribe el comando %timeit seguido de la suma directa de ambos arreglos (array_A + array_B).