# (Listas vs. Arrays)

En Python nativo, usamos listas que pueden guardar cualquier tipo de objeto (texto, números, booleanos). Sin embargo, para la Ciencia de Datos, procesar millones de registros de esta forma es muy lento. NumPy introduce el ndarray (arreglos de N-dimensiones), bloques de datos del mismo tipo que se almacenan juntos en la memoria del computador, permitiendo cálculos  veloces.

Ejemplo
Python

In [ ]:
import numpy as np

# Creación de un vector simple
lista_precios = [10, 20, 30]
array_precios = np.array(lista_precios)

print("Lista con comas:", lista_precios)
print("Array NumPy (notar que no tiene comas):", array_precios)

Lista con comas: [10, 20, 30]
Array NumPy (notar que no tiene comas): [10 20 30]


## Ejercicio 3
Imagina que recibimos las primeras lecturas de temperatura de un sensor agrícola.

Crea una lista de Python llamada lecturas_lista con los valores: [21, 24, 23, 26, 25].

Convierte esa lista en un array de NumPy llamado lecturas_array.

Imprime ambos en pantalla. Añade una celda de código abajo ejecutando print(lecturas_array.dtype) y observa qué tipo de dato infirió NumPy.

In [ ]:
lecturas_lista = [21, 24, 23, 26, 25]
lecturas_array = np.array(lecturas_lista)

print(lecturas_lista, type(lecturas_lista))
print(lecturas_array, type(lecturas_array))

[21, 24, 23, 26, 25] <class 'list'>
[21 24 23 26 25] <class 'numpy.ndarray'>


# (Vectorización)

Si queremos sumarle un valor a cada elemento de una lista de Python, estamos obligados a escribir un ciclo for que recorra la estructura elemento por elemento. En NumPy existe la vectorización: las operaciones matemáticas se aplican a todo el bloque al mismo tiempo directamente a nivel de hardware.

Podemos anteponer el comando  %timeit al principio de una celda para medir de forma real cuántos milisegundos (ms) o microsegundos (µs) tarda en ejecutarse un bloque de código.

Otra forma de medir de forma exacta cuánto tarda en ejecutarse un bloque de código en cualquier entorno (ya sea una celda de Google Colab o un script en Visual Studio Code), podemos usar la librería nativa de Python llamada time.

La estrategia consiste en guardar la hora actual antes de que empiece el cálculo con time.time(), ejecutar el proceso y volver a tomar la hora al finalizar. Al restar el tiempo final menos el tiempo inicial, obtenemos los segundos exactos que tardó la computadora en procesar la operación.

In [ ]:
#Ejemplo
import time

inicio = time.time()
# ... aquí va el proceso que queremos medir ...
fin = time.time()

tiempo_total = fin - inicio
print("El proceso tardó:",tiempo_total, "segundos.")

In [ ]:
# Error en Python nativo: lista + 1 dará un TypeError.
# Acierto en NumPy:
import numpy as np
numeros = np.array([1, 2, 3])
print(numeros + 5)  # Resultado: [6, 7, 8]

# Ejercicio 4
Vamos a simular un millón de registros de producción agrícola para comparar velocidades. Escribe el siguiente código en otra celda separada y optimizarla con numpy:

Pregunta de reflexión: Compara los tiempos de ejecución obtenidos. ¿Qué unidad de medida de tiempo utilizó cada celda y aproximadamente cuántas veces fue más rápido NumPy?

Celda A (Python Nativo):

In [1]:
import time

# 1. Crear las listas grandes
lista_A = list(range(1000000))
lista_resultado = []

# 2. Capturar el tiempo de inicio
inicio_lista = time.time()

# 3. Ejecutar el bucle manual elemento por elemento
for valor in lista_A:
    lista_resultado.append(valor + 2)

# 4. Capturar el tiempo de finalización y calcular la diferencia
fin_lista = time.time()
tiempo_lista = fin_lista - inicio_lista

print("Tiempo con Listas Nativas:", tiempo_lista, "segundos.")

Tiempo con Listas Nativas: 0.054837703704833984 segundos.


Celda B (NumPy Vectorizado):

In [2]:
import numpy as np
## Escribe la instrucción utilizando %timeit en una sola línea
## para medir cuánto tarda crear un np.arange(1000000) y sumarle 2.
%timeit np.arange(1000000) + 2




375 μs ± 2.87 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Estructuración de Datos en Matrices (Shape & Reshape)

Los datos tabulares del mundo real (filas y columnas) se representan en NumPy como arrays bidimensionales o matrices. Todo array posee una propiedad fundamental llamada .shape, que nos devuelve una tupla con sus dimensiones (filas, columnas). Podemos cambiar la forma o estructura de un array mediante el método .reshape() sin alterar los datos internos.

Ejemplo

In [3]:
import numpy as np
# Creamos un vector de 6 elementos y lo reestructuramos en una matriz de 2x3
vector = np.arange(6)
matriz = vector.reshape(2, 3)
print(matriz)
print("Dimensiones:", matriz.shape)

[[0 1 2]
 [3 4 5]]
Dimensiones: (2, 3)


# Ejercicio 5

Tenemos un lote consecutivo de 12 mediciones de humedad del suelo, y sabemos que corresponden a un monitoreo estructurado en 4 zonas con 3 sensores en cada una.

Genera un array unidimensional usando np.arange(12).

Utiliza .reshape() para transformar esos 12 datos en una matriz de 4 filas (zonas) y 3 columnas (sensores). Imprime el resultado.

¿Qué ocurre si intentas aplicar un .reshape(5, 3) sobre ese array de 12 elementos? Justifica la respuesta según el error observado.

In [25]:
arrayUni = np.arange(12)
print(arrayUni, "\n")
uniReshapeado = arrayUni.reshape(4, 3)
print(uniReshapeado)
# print(arrayUni.reshape(4,3))
# print(arrayUni.reshape(5,3)) #* Me da error debido a que el tamaño no posibilita transformar la matriz en una de 5 filas y 3 columnas.

[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


# Reducción y Operaciones Estadísticas (.sum())

Cuando trabajamos con grandes volúmenes de información, necesitamos resumir los datos rápidamente. Las listas nativas no tienen metodos estadísticos embebidos (escribir lista.sum() dará un error de atributo), pero los objetos de NumPy incluyen métodos optimizados de agregación listos para usar en sus estructuras como .sum(), .mean(), .max(), etc.

# Ejercicio 6

Utilizando la matriz de variables agrícolas de 4x3 generada en el ejercicio anterior:

Aplica el método correspondiente para calcular la suma total de todas las mediciones combinadas en el array.

Investiga en la documentación o probando el código: ¿Cómo puedes calcular el promedio de la humedad usando el método .mean()?

Intenta calcular la suma usando la función nativa sum(matriz_humedad) y luego usando el método propio matriz_humedad.sum(). ¿Cuál de los dos te devuelve la estructura matemática limpia del bloque?

In [17]:
print("suma de elementos: ", arrayUni.sum())
print("promedio: ", arrayUni.mean())
print("numero maximo del array: ", arrayUni.max())
print("numero minimo del array: ", arrayUni.min())

print("SUM nativo: ", sum(arrayUni))
print("SUM numpy: ", arrayUni.sum())

suma de elementos:  66
promedio:  5.5
numero maximo del array:  11
numero minimo del array:  0
SUM nativo:  66
SUM numpy:  66


# Inspección de Estructuras (Atributos de los Arrays)

El PDF de teoría nos detalla que cada array de NumPy posee propiedades internas esenciales para conocer la naturaleza de nuestros datos sin necesidad de imprimirlos por completo:

ndim: Devuelve el número de dimensiones (ejes) del array.

size: Nos indica la cantidad total de elementos que contiene.

dtype: Muestra el tipo de datos de los elementos (ej. int32, float64).

In [ ]:
import numpy as np
# matriz_ejemplo = np.array([[1, 2], [3, 4]])
matriz_ejemplo = np.array([["mat", "riz"], ["ho", "la"]])

print("Número de dimensiones:", matriz_ejemplo.ndim)  # Devuelve: 2
print("Cantidad total de elementos:", matriz_ejemplo.size)  # Devuelve: 4
print("Cantidad total de elementos:", matriz_ejemplo.dtype)  # Devuelve: U3 (Unicode, 3caracteres el elemento mas largo)

Número de dimensiones: 2
Cantidad total de elementos: 4
Cantidad total de elementos: <U3


# Ejercicio 7

A partir de la matriz de mediciones de humedad que creaste en el ejercicio 5 (de 4 filas y 3 columnas):

Escribe el código necesario para imprimir en la consola de forma ordenada sus tres atributos básicos: ndim, size y dtype.

Pregunta de observación: ¿Qué valor te devuelve el atributo ndim? ¿Coincide con el concepto de que una estructura con filas y columnas es bidimensional?

In [ ]:
print("tamaño de Matriz: ", uniReshapeado.ndim) #* 2 por que si tiene filas y columnas es BIdimensional
print("cantidad de elementos: ", uniReshapeado.size) 
print("tipo de elementos: ", uniReshapeado.dtype) 

tamaño de Matriz:  2
cantidad de elementos:  12
tipo de elementos:  int64


# Inicialización Automatizada (zeros y ones)

En Ciencia de Datos, muchas veces necesitamos crear estructuras vacías o preestablecidas antes de llenarlas con cálculos reales. Tal como explica el apunte teórico, NumPy provee funciones optimizadas para esto:

np.zeros(forma): Crea un array lleno de ceros.

np.ones(forma): Crea un array lleno de unos.
(Nota: Para matrices bidimensionales, la forma o "shape" debe pasarse entre un doble paréntesis, por ejemplo: np.zeros((filas, columnas))).

In [29]:
import numpy as np
# Crear una matriz vacía de prueba de 2 filas y 5 columnas
matriz_vacia = np.zeros((2, 5))
print(matriz_vacia, "\n")
matriz_unos = np.ones((3,3))
print(matriz_unos)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Ejercicio 8

Imagina que vas a diseñar un nuevo mapa digital de un lote de campo dividido en una cuadrícula de 3 parcelas de largo por 6 parcelas de ancho. Al principio, ninguna parcela tiene plantaciones (valor inicial 0).

Crea una matriz llamada mapa_lote llena de ceros utilizando la función correspondiente, asegurando que tenga 3 filas y 6 columnas.

Imprime la matriz en pantalla para verificar que la cuadrícula se haya creado correctamente.

In [30]:
loteCampo = np.zeros((3,6))
print(loteCampo)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


# Segmentación e Indexación Condicional (Máscaras Booleanas)

El PDF destaca una de las herramientas más potentes de NumPy: la capacidad de filtrar elementos utilizando condiciones lógicas (operadores como >, <, ==). Al aplicar una condición a un array, NumPy evalúa cada celda y genera una "máscara booleana" (de valores True o False). Si pasamos esa máscara al array original, se extraerán únicamente los elementos que cumplan la condición.

Ejemplo

In [34]:
import numpy as np
edades = np.array([20, 45, 18, 30])
# edades = [20, 45, 18, 30]
mayores_de_25 = edades[edades > 25]
print(mayores_de_25)  # Devuelve: [45, 30]

[45 30]


# Ejercicio 9
Supongamos que tenemos un array unidimensional con los registros de temperatura tomados en un invernadero a lo largo del día:

In [36]:
temperaturas = np.array([22.5, 24.1, 28.3, 31.0, 29.4, 21.8, 33.5, 26.0])

Escribe una línea de código que filtre el array anterior para extraer y guardar en una nueva variable llamada alertas_calor únicamente aquellas temperaturas que sean estrictamente mayores a 28.0 grados.

Imprime el resultado en pantalla.

Pregunta de análisis: ¿Cuántas lecturas del día superaron el límite de alerta establecido?

In [42]:
alertasCalor = temperaturas[temperaturas > 28.0]
print("Temperaturas Superiores: ", alertasCalor)
print("Cantidad de temperaturas superiores: ", alertasCalor.size)

Temperaturas Superiores:  [28.3 31.  29.4 33.5]
Cantidad de temperaturas superiores:  4


# (Crecimiento Secuencial de Fibonacci)

En la naturaleza y la agricultura, muchas estructuras siguen patrones secuenciales de crecimiento como la famosa Sucesión de Fibonacci. En este paso final, analizaremos cómo se comporta la relación entre términos contiguos para observar cómo converge hacia el Número Áureo ($\Phi \approx 1.618$).

Ejemplo

Si tenemos una lista de Fibonacci inicial [0, 1, 1, 2, 3, 5, 8], podemos acceder a los últimos elementos usando índices negativos (por ejemplo, fibo[-1] para el último valor).

# (Ejercicio 9 - Desafío Final)

Asumiendo que ya posees una lista con los primeros 30 números de la sucesión de Fibonacci llamada fibo:Crea un bucle que recorra los últimos 5 pares de números contiguos de tu lista de datos.En cada iteración, calcula el cociente dividiendo el término actual por su término inmediatamente anterior ($n_i / n_{i-1}$) e imprime los resultados en pantalla.

Pregunta de cierre: Observando los 5 resultados impresos en la consola, ¿a qué valor decimal fijo se aproximan de forma matemática constante?

In [47]:
fibo = [0, 1]

for _ in range(28):
    nextNumber = fibo[-2] + fibo[-1]
    fibo.append(nextNumber)  

# Creamos el bucle para recorrer los índices desde el 25 hasta el 29
for i in range(25, 30):
    termino_actual = fibo[i]
    termino_anterior = fibo[i - 1]
    
    # Calculamos el cociente
    cociente = termino_actual / termino_anterior
    
    # Imprimimos los resultados en pantalla
    print(f"División de {termino_actual} / {termino_anterior} = {cociente}")

División de 75025 / 46368 = 1.618033988957902
División de 121393 / 75025 = 1.6180339886704431
División de 196418 / 121393 = 1.6180339887802426
División de 317811 / 196418 = 1.618033988738303
División de 514229 / 317811 = 1.6180339887543225
